# SwiftLint configuration file
# Customize these rules based on your project's needs

disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - function_body_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - private_outlet
  - unneeded_parentheses_in_closure_argument

included:
  - JITEnabler

excluded:
  - Pods
  - DerivedData
  - .build

analyzer_rules:
  - unused_declaration
  - unused_import

force_cast: warning
force_try: warning
force_unwrapping: warning

function_parameter_count:
  warning: 8
  error: 10

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 3
  max_length: 50

large_tuple:
  warning: 3
  error: 5

reporter: "xcode"
